version: '3.9'

services:
  db:
    image: "postgres:14.0-alpine"
    restart: always
    environment:
      POSTGRES_USER: warehouse_user
      POSTGRES_PASSWORD: warehouse_user_password
      POSTGRES_DB: warehouse_db
    ports:
      - "5432:5432"
    volumes:
      - "./storage/migrations:/docker-entrypoint-initdb.d/"
  app:
    build:
      dockerfile: Dockerfile
      context: .
    links:
      - db
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/warehouse_db"



